[package]
name = "libecdsautil-sys"
description = "Unsafe bindings for libecdsautil."
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
